#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

cookbook 'apt'
cookbook 'openssl'
cookbook 'build-essential'
cookbook 'ruby_build'
cookbook 'sqlite'
cookbook 'rbenv', :git => 'git://github.com/fnichol/chef-rbenv.git'#, :ref
cookbook 'nodejs'
#cookbook 'git'